version: '3.8'

services:
  blog:
    container_name: "sonsu-blog"
    build:
      context: ./
      target: develop-stage
      dockerfile: dev.Dockerfile
    ports:
      - ${APP_PORT:-3000}:3000
    environment:
      - NODE_ENV=${NODE_ENV}
    volumes:
      - ./:/home/blog
      - /home/blog/node_modules